name: Biome Lint

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.2.21'
      - name: Install deps
        run: bun install --frozen-lockfile
      - name: Run Biome lint
        run: bunx biome lint .
