name: Refactor Gates (Bun)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  refactor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.2.21'
      - name: Prepare Bun tmp dirs
        run: |
          echo "BUN_TMPDIR=$GITHUB_WORKSPACE/.bun-tmp" >> $GITHUB_ENV
          echo "BUN_INSTALL=$HOME/.bun" >> $GITHUB_ENV
          mkdir -p "$GITHUB_WORKSPACE/.bun-tmp"
      - name: Install deps
        run: bun install
      - name: Run refactor orchestrator
        run: bun scripts/orchestrate-refactor-phase-1.cjs
      - name: Upload usage audit
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: usage-audit
          path: .reports/assets/usage-audit.json

